version: "3"
envfile: .env
server:
  command: "php psr-worker.php"
  relay: pipes
metrics:
  address: 0.0.0.0:2112
  collect:
    produced_materials:
      type: counter
      help: Number of materials produced by factories
      labels:
        - material_name
        - material_id
    consumed_materials:
      type: counter
      help: Number of materials consumed by factories
      labels:
        - material_name
        - material_id
    sold_materials:
      type: counter
      help: Number of materials sold by wildcard factories
      labels:
        - material_name
        - material_id
    transported_materials:
      type: gauge
      help: Number of materials currently in transport
      labels:
        - material_name
        - material_id
    loaded_materials:
      type: counter
      help: Number of materials loaded by connections from factories
      labels:
        - material_name
        - material_id
    unloaded_materials:
      type: counter
      help: Number of materials unloaded by connections at factories
      labels:
        - material_name
        - material_id
    active_connections:
      type: gauge
      help: Currently running connections
    assigned_connections:
      type: gauge
      help: Currently running connections
rpc:
  listen: tcp://0.0.0.0:6001
http:
  address: 0.0.0.0:8001
  access_logs: true
  middleware:
    - headers
    - http_metrics
  pool:
    num_workers: 5
    max_queue_size: 10
    supervisor:
      max_worker_memory: 512
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
      # Status code to use for successful OPTIONS requests. Default value is 200.
      options_success_status: 200
  fcgi:
    address: tcp://0.0.0.0:9000
amqp:
  addr: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
jobs:
  num_pollers: 10
  timeout: 120
  pipeline_size: 1000
  pool:
    num_workers: 10
    supervisor:
      max_worker_memory: 512
  consume: [ "commands" ]
  pipelines:
    commands:
      driver: amqp
      config:
        queue: commands
        durable: true
        routing_key: commands
logs:
  encoding: console
  level: debug
  mode: development