{
 "title": "Application",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running / Stopped factories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  IF (\n    has_all_materials = 1\n    AND (storage_capacity - stored) >= out_size,\n    'Running',\n    'Stopped'\n  ) AS Label,\n  COUNT(*) AS value\nFROM\n  (\n    SELECT\n      f.*,\n      COALESCE(SUM(s.quantity * m.size), 0) as `stored`,\n      (\n        SELECT\n          COALESCE(SUM(po.quantity * pm.size), 0)\n        FROM\n          processes po\n          JOIN materials pm ON po.id_material = pm.id_material\n          AND po.id_factory = f.id_factory\n          AND po.type = 'out'\n      ) as `out_size`,\n      IF(\n        COUNT(DISTINCT p.id_material) = SUM(IF(COALESCE(ps.quantity, 0) >= p.quantity, 1, 0)),\n        1,\n        0\n      ) AS has_all_materials\n    FROM\n      factories f\n      LEFT JOIN factory_storage s ON f.id_factory = s.id_factory\n      LEFT JOIN materials m ON m.id_material = s.id_material\n      LEFT JOIN processes p ON (\n        p.id_factory = f.id_factory\n        AND p.type = 'in'\n      )\n      LEFT JOIN factory_storage ps ON (\n        f.id_factory = ps.id_factory\n        AND p.id_material = ps.id_material\n      )\n    GROUP BY\n      f.id_factory\n  ) a\nGROUP BY\n  Label"
    }
   ]
  },
  {
   "title": "Produced materials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(produced_materials[1m])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  },
  {
   "title": "Sold materials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sold_materials[1m])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  },
  {
   "title": "Consumed materials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(consumed_materials[1m])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "assigned_connections", "legendFormat": "Assigned connections" },
    { "expr": "active_connections", "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "Transported materials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(transported_materials[1m])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  }
 ]
}