# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: roadrunner
    static_configs:
      - targets:
          - "php:2112"
  - job_name: rabbitmq
    static_configs:
        - targets:
            - "rabbitmq:15692"
    scrape_interval: 30s
