{
 "title": "Application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Produced materials",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(produced_materials[$__rate_interval])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  },
  {
   "title": "Consumed materials",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(consumed_materials[$__rate_interval])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  },
  {
   "title": "Running / Stopped factories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\n  IF (\n    has_all_materials = 1\n    AND (storage_capacity - stored) >= (out_size - in_size),\n    'Running',\n    'Stopped'\n  ) AS Label,\n  COUNT(*) AS value\nFROM\n  (\n    SELECT f.*,\n       (SELECT\n            COALESCE(SUM(s.quantity * m.size), 0)\n        FROM factory_storage s\n        JOIN materials m ON s.id_material = m.id_material\n        WHERE s.id_factory = f.id_factory\n            ) as `stored`,\n       (SELECT COALESCE(SUM(po.quantity * pm.size), 0)\n        FROM processes po\n                 JOIN materials pm ON po.id_material = pm.id_material\n            AND po.id_factory = f.id_factory\n            AND po.type = 'in')             as `in_size`,\n       (SELECT COALESCE(SUM(po.quantity * pm.size), 0)\n        FROM processes po\n                 JOIN materials pm ON po.id_material = pm.id_material\n            AND po.id_factory = f.id_factory\n            AND po.type = 'out')             as `out_size`,\n\n       IF(\n               COUNT(DISTINCT p.id_material) = SUM(IF(COALESCE(ps.quantity, 0) >= p.quantity, 1, 0)),\n               1,\n               0\n       )                                     AS has_all_materials\nFROM factories f\n         LEFT JOIN processes p ON (p.id_factory = f.id_factory AND p.type = 'in')\n         LEFT JOIN factory_storage ps ON (f.id_factory = ps.id_factory AND p.id_material = ps.id_material)\nGROUP BY f.id_factory\n  ) a\nGROUP BY\n  Label"
    }
   ]
  },
  {
   "title": "Sold materials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(sold_materials[$__rate_interval])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "assigned_connections", "legendFormat": "Assigned connections" },
    { "expr": "active_connections", "legendFormat": "Active connections" }
   ]
  },
  {
   "title": "Transported materials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(transported_materials[$__rate_interval])",
     "legendFormat": "{{material_name}} ({{material_id}})"
    }
   ]
  }
 ]
}